#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : linuxptp
Version  : 1.9.2
Release  : 2
URL      : https://cytranet.dl.sourceforge.net/project/linuxptp/v1.9/linuxptp-1.9.2.tgz
Source0  : https://cytranet.dl.sourceforge.net/project/linuxptp/v1.9/linuxptp-1.9.2.tgz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: linuxptp-bin
Requires: linuxptp-doc
Patch1: 0001-Set-standard-Clear-Linux-installation-paths.patch

%description
* Introduction
This software is an implementation of the Precision Time Protocol
(PTP) according to IEEE standard 1588 for Linux. The dual design
goals are to provide a robust implementation of the standard and to
use the most relevant and modern Application Programming Interfaces
(API) offered by the Linux kernel. Supporting legacy APIs and other
platforms is not a goal.

%package bin
Summary: bin components for the linuxptp package.
Group: Binaries

%description bin
bin components for the linuxptp package.


%package doc
Summary: doc components for the linuxptp package.
Group: Documentation

%description doc
doc components for the linuxptp package.


%prep
%setup -q -n linuxptp-1.9.2
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1523652148
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1523652148
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/hwstamp_ctl
/usr/bin/nsm
/usr/bin/phc2sys
/usr/bin/phc_ctl
/usr/bin/pmc
/usr/bin/ptp4l
/usr/bin/timemaster

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man8/*
