#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : linuxptp
Version  : 3.1
Release  : 6
URL      : https://sourceforge.net/projects/linuxptp/files/v3.1/linuxptp-3.1.tgz
Source0  : https://sourceforge.net/projects/linuxptp/files/v3.1/linuxptp-3.1.tgz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: linuxptp-bin = %{version}-%{release}
Requires: linuxptp-license = %{version}-%{release}
Requires: linuxptp-man = %{version}-%{release}
Patch1: 0001-Set-standard-Clear-Linux-installation-paths.patch

%description
* Introduction
This software is an implementation of the Precision Time Protocol
(PTP) according to IEEE standard 1588 for Linux. The dual design
goals are to provide a robust implementation of the standard and to
use the most relevant and modern Application Programming Interfaces
(API) offered by the Linux kernel. Supporting legacy APIs and other
platforms is not a goal.

%package bin
Summary: bin components for the linuxptp package.
Group: Binaries
Requires: linuxptp-license = %{version}-%{release}

%description bin
bin components for the linuxptp package.


%package license
Summary: license components for the linuxptp package.
Group: Default

%description license
license components for the linuxptp package.


%package man
Summary: man components for the linuxptp package.
Group: Default

%description man
man components for the linuxptp package.


%prep
%setup -q -n linuxptp-3.1
cd %{_builddir}/linuxptp-3.1
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1601314765
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1601314765
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/linuxptp
cp %{_builddir}/linuxptp-3.1/COPYING %{buildroot}/usr/share/package-licenses/linuxptp/4cc77b90af91e615a64ae04893fdffa7939db84c
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/hwstamp_ctl
/usr/bin/nsm
/usr/bin/phc2sys
/usr/bin/phc_ctl
/usr/bin/pmc
/usr/bin/ptp4l
/usr/bin/timemaster
/usr/bin/ts2phc

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/linuxptp/4cc77b90af91e615a64ae04893fdffa7939db84c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/hwstamp_ctl.8
/usr/share/man/man8/nsm.8
/usr/share/man/man8/phc2sys.8
/usr/share/man/man8/phc_ctl.8
/usr/share/man/man8/pmc.8
/usr/share/man/man8/ptp4l.8
/usr/share/man/man8/timemaster.8
/usr/share/man/man8/ts2phc.8
